#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DDBD")]
	public partial class QLDDBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public QLDDBDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DDBDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BanDo> BanDos
		{
			get
			{
				return this.GetTable<BanDo>();
			}
		}
		
		public System.Data.Linq.Table<MocDoCao> MocDoCaos
		{
			get
			{
				return this.GetTable<MocDoCao>();
			}
		}
		
		public System.Data.Linq.Table<MocToaDo> MocToaDos
		{
			get
			{
				return this.GetTable<MocToaDo>();
			}
		}
		
		public System.Data.Linq.Table<MocTrongLuc> MocTrongLucs
		{
			get
			{
				return this.GetTable<MocTrongLuc>();
			}
		}
	}
	
	[Table(Name="dbo.BANDO")]
	public partial class BanDo
	{
		
		private int _OBJECTID;
		
		private string _MaBanDo;
		
		private System.Nullable<decimal> _MaSanPham;
		
		private System.Nullable<int> _MaLoaiBanDo;
		
		private string _NamThucHien;
		
		private string _NamHoanThanh;
		
		private string _NamChinhLy;
		
		private System.Nullable<int> _TiLe;
		
		private System.Nullable<int> _Shape;
		
		public BanDo()
		{
		}
		
		[Column(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[Column(Storage="_MaBanDo", DbType="NVarChar(255)")]
		public string MaBanDo
		{
			get
			{
				return this._MaBanDo;
			}
			set
			{
				if ((this._MaBanDo != value))
				{
					this._MaBanDo = value;
				}
			}
		}
		
		[Column(Storage="_MaSanPham", DbType="Decimal(38,8)")]
		public System.Nullable<decimal> MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this._MaSanPham = value;
				}
			}
		}
		
		[Column(Storage="_MaLoaiBanDo", DbType="Int")]
		public System.Nullable<int> MaLoaiBanDo
		{
			get
			{
				return this._MaLoaiBanDo;
			}
			set
			{
				if ((this._MaLoaiBanDo != value))
				{
					this._MaLoaiBanDo = value;
				}
			}
		}
		
		[Column(Storage="_NamThucHien", DbType="NVarChar(255)")]
		public string NamThucHien
		{
			get
			{
				return this._NamThucHien;
			}
			set
			{
				if ((this._NamThucHien != value))
				{
					this._NamThucHien = value;
				}
			}
		}
		
		[Column(Storage="_NamHoanThanh", DbType="NVarChar(255)")]
		public string NamHoanThanh
		{
			get
			{
				return this._NamHoanThanh;
			}
			set
			{
				if ((this._NamHoanThanh != value))
				{
					this._NamHoanThanh = value;
				}
			}
		}
		
		[Column(Storage="_NamChinhLy", DbType="NVarChar(255)")]
		public string NamChinhLy
		{
			get
			{
				return this._NamChinhLy;
			}
			set
			{
				if ((this._NamChinhLy != value))
				{
					this._NamChinhLy = value;
				}
			}
		}
		
		[Column(Storage="_TiLe", DbType="Int")]
		public System.Nullable<int> TiLe
		{
			get
			{
				return this._TiLe;
			}
			set
			{
				if ((this._TiLe != value))
				{
					this._TiLe = value;
				}
			}
		}
		
		[Column(Storage="_Shape", DbType="Int")]
		public System.Nullable<int> Shape
		{
			get
			{
				return this._Shape;
			}
			set
			{
				if ((this._Shape != value))
				{
					this._Shape = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.MOCDOCAO")]
	public partial class MocDoCao
	{
		
		private int _OBJECTID;
		
		private string _SoHieu;
		
		private System.Nullable<int> _MaSanPham;
		
		private System.Nullable<int> _CapHang;
		
		private System.Nullable<int> _LoaiMoc;
		
		private string _HeQuyChieu;
		
		private string _HeDoCao;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _NamThanhLap;
		
		private System.Nullable<int> _Shape;
		
		public MocDoCao()
		{
		}
		
		[Column(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[Column(Storage="_SoHieu", DbType="NVarChar(255)")]
		public string SoHieu
		{
			get
			{
				return this._SoHieu;
			}
			set
			{
				if ((this._SoHieu != value))
				{
					this._SoHieu = value;
				}
			}
		}
		
		[Column(Storage="_MaSanPham", DbType="Int")]
		public System.Nullable<int> MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this._MaSanPham = value;
				}
			}
		}
		
		[Column(Storage="_CapHang", DbType="Int")]
		public System.Nullable<int> CapHang
		{
			get
			{
				return this._CapHang;
			}
			set
			{
				if ((this._CapHang != value))
				{
					this._CapHang = value;
				}
			}
		}
		
		[Column(Storage="_LoaiMoc", DbType="Int")]
		public System.Nullable<int> LoaiMoc
		{
			get
			{
				return this._LoaiMoc;
			}
			set
			{
				if ((this._LoaiMoc != value))
				{
					this._LoaiMoc = value;
				}
			}
		}
		
		[Column(Storage="_HeQuyChieu", DbType="NVarChar(255)")]
		public string HeQuyChieu
		{
			get
			{
				return this._HeQuyChieu;
			}
			set
			{
				if ((this._HeQuyChieu != value))
				{
					this._HeQuyChieu = value;
				}
			}
		}
		
		[Column(Storage="_HeDoCao", DbType="NVarChar(255)")]
		public string HeDoCao
		{
			get
			{
				return this._HeDoCao;
			}
			set
			{
				if ((this._HeDoCao != value))
				{
					this._HeDoCao = value;
				}
			}
		}
		
		[Column(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[Column(Storage="_NamThanhLap", DbType="NVarChar(255)")]
		public string NamThanhLap
		{
			get
			{
				return this._NamThanhLap;
			}
			set
			{
				if ((this._NamThanhLap != value))
				{
					this._NamThanhLap = value;
				}
			}
		}
		
		[Column(Storage="_Shape", DbType="Int")]
		public System.Nullable<int> Shape
		{
			get
			{
				return this._Shape;
			}
			set
			{
				if ((this._Shape != value))
				{
					this._Shape = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.MOCTOADO")]
	public partial class MocToaDo
	{
		
		private int _OBJECTID;
		
		private string _SoHieu;
		
		private System.Nullable<int> _MaSanPham;
		
		private System.Nullable<int> _CapHang;
		
		private System.Nullable<int> _LoaiMoc;
		
		private string _HeQuyChieu;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _NamThanhLap;
		
		private System.Nullable<int> _Shape;
		
		public MocToaDo()
		{
		}
		
		[Column(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[Column(Storage="_SoHieu", DbType="NVarChar(255)")]
		public string SoHieu
		{
			get
			{
				return this._SoHieu;
			}
			set
			{
				if ((this._SoHieu != value))
				{
					this._SoHieu = value;
				}
			}
		}
		
		[Column(Storage="_MaSanPham", DbType="Int")]
		public System.Nullable<int> MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this._MaSanPham = value;
				}
			}
		}
		
		[Column(Storage="_CapHang", DbType="Int")]
		public System.Nullable<int> CapHang
		{
			get
			{
				return this._CapHang;
			}
			set
			{
				if ((this._CapHang != value))
				{
					this._CapHang = value;
				}
			}
		}
		
		[Column(Storage="_LoaiMoc", DbType="Int")]
		public System.Nullable<int> LoaiMoc
		{
			get
			{
				return this._LoaiMoc;
			}
			set
			{
				if ((this._LoaiMoc != value))
				{
					this._LoaiMoc = value;
				}
			}
		}
		
		[Column(Storage="_HeQuyChieu", DbType="NVarChar(255)")]
		public string HeQuyChieu
		{
			get
			{
				return this._HeQuyChieu;
			}
			set
			{
				if ((this._HeQuyChieu != value))
				{
					this._HeQuyChieu = value;
				}
			}
		}
		
		[Column(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[Column(Storage="_NamThanhLap", DbType="NVarChar(255)")]
		public string NamThanhLap
		{
			get
			{
				return this._NamThanhLap;
			}
			set
			{
				if ((this._NamThanhLap != value))
				{
					this._NamThanhLap = value;
				}
			}
		}
		
		[Column(Storage="_Shape", DbType="Int")]
		public System.Nullable<int> Shape
		{
			get
			{
				return this._Shape;
			}
			set
			{
				if ((this._Shape != value))
				{
					this._Shape = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.MOCTRONGLUC")]
	public partial class MocTrongLuc
	{
		
		private int _OBJECTID;
		
		private string _SoHieu;
		
		private System.Nullable<int> _MaSanPham;
		
		private System.Nullable<int> _CapHang;
		
		private System.Nullable<int> _LoaiMoc;
		
		private string _HeQuyChieu;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _NamThanhLap;
		
		private System.Nullable<int> _Shape;
		
		public MocTrongLuc()
		{
		}
		
		[Column(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[Column(Storage="_SoHieu", DbType="NVarChar(255)")]
		public string SoHieu
		{
			get
			{
				return this._SoHieu;
			}
			set
			{
				if ((this._SoHieu != value))
				{
					this._SoHieu = value;
				}
			}
		}
		
		[Column(Storage="_MaSanPham", DbType="Int")]
		public System.Nullable<int> MaSanPham
		{
			get
			{
				return this._MaSanPham;
			}
			set
			{
				if ((this._MaSanPham != value))
				{
					this._MaSanPham = value;
				}
			}
		}
		
		[Column(Storage="_CapHang", DbType="Int")]
		public System.Nullable<int> CapHang
		{
			get
			{
				return this._CapHang;
			}
			set
			{
				if ((this._CapHang != value))
				{
					this._CapHang = value;
				}
			}
		}
		
		[Column(Storage="_LoaiMoc", DbType="Int")]
		public System.Nullable<int> LoaiMoc
		{
			get
			{
				return this._LoaiMoc;
			}
			set
			{
				if ((this._LoaiMoc != value))
				{
					this._LoaiMoc = value;
				}
			}
		}
		
		[Column(Storage="_HeQuyChieu", DbType="NVarChar(255)")]
		public string HeQuyChieu
		{
			get
			{
				return this._HeQuyChieu;
			}
			set
			{
				if ((this._HeQuyChieu != value))
				{
					this._HeQuyChieu = value;
				}
			}
		}
		
		[Column(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[Column(Storage="_NamThanhLap", DbType="NVarChar(255)")]
		public string NamThanhLap
		{
			get
			{
				return this._NamThanhLap;
			}
			set
			{
				if ((this._NamThanhLap != value))
				{
					this._NamThanhLap = value;
				}
			}
		}
		
		[Column(Storage="_Shape", DbType="Int")]
		public System.Nullable<int> Shape
		{
			get
			{
				return this._Shape;
			}
			set
			{
				if ((this._Shape != value))
				{
					this._Shape = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
